<?php

namespace Brouwkuyp\Bundle\ServiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ControlRecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ControlRecipeRepository extends EntityRepository
{
}
