<?php

namespace Brouwkuyp\Bundle\ServiceBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends EntityRepository
{
    /**
     * @return QueryBuilder
     */
    public function getBaseQueryBuilder()
    {
        $qb = $this->createQueryBuilder('l')
            ->orderBy('l.createdAt', 'ASC')
        ;

        return $qb;
    }

    /**
     * @return array
     */
    public function findForCurrentRecipe()
    {
        $qb = $this->getBaseQueryBuilder()
            ->andWhere('DATE(l.createdAt) = :date')
            ->setParameter('date', (new \DateTime())->format('Y-m-d'))
        ;

        return $qb->getQuery()->execute();
    }
}
