<?php

namespace Brouwkuyp\Bundle\ServiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UnitProcedureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitProcedureRepository extends EntityRepository
{
}
