services:
    brouwkuyp_service.repository.control_recipe:
        class: Brouwkuyp\Bundle\ServiceBundle\Repository\ControlRecipeRepository
        factory: ['@doctrine', 'getRepository']
        arguments:
            - Brouwkuyp\Bundle\ServiceBundle\Entity\ControlRecipe

    brouwkuyp_service.repository.log:
        class: Brouwkuyp\Bundle\ServiceBundle\Repository\LogRepository
        factory: ['@doctrine', 'getRepository']
        arguments:
            - Brouwkuyp\Bundle\ServiceBundle\Entity\Log

    brouwkuyp_service.repository.batch:
        class: Brouwkuyp\Bundle\ServiceBundle\Repository\BatchRepository
        factory: ['@doctrine', 'getRepository']
        arguments:
            - Brouwkuyp\Bundle\ServiceBundle\Entity\Batch

    brouwkuyp_service.repository.phase:
        class: Brouwkuyp\Bundle\ServiceBundle\Repository\PhaseRepository
        factory: ['@doctrine', 'getRepository']
        arguments:
            - Brouwkuyp\Bundle\ServiceBundle\Entity\Phase
