services:

    brouwkuyp_service.manager.brew_control:
        alias: brouwkuyp_service.amqp.manager.brew_control

    brouwkuyp_service.amqp.connection:
        class: PhpAmqpLib\Connection\AMQPStreamConnection
        arguments:
            - '%rabbit_mq_host%'
            - 5672
            - guest
            - guest

    brouwkuyp_service.amqp.manager:
        class: Brouwkuyp\Bundle\ServiceBundle\Manager\AMQP\Manager
        arguments:
            - @brouwkuyp_service.amqp.connection
        calls:
            - [ setLogger, [ @logger ]]

    brouwkuyp_service.amqp.manager.brew_control:
        class: Brouwkuyp\Bundle\ServiceBundle\Manager\AMQP\BrewControlManager
        arguments:
            - @brouwkuyp_service.amqp.manager

    brouwkuyp_service.amqp.manager.log:
        class: Brouwkuyp\Bundle\ServiceBundle\Manager\AMQP\LogManager
        arguments:
            - @brouwkuyp_service.amqp.manager
