imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    secret:             '%secret%'
    router:
        resource:       '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: false }
    templating:
        engines: ['twig']
    default_locale:  '%locale%'
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:              '%kernel.debug%'
    strict_variables:   '%kernel.debug%'
    globals:
        domain:         '%domain%'

# Assetic Configuration
assetic:
    debug:              '%kernel.debug%'
    use_controller:     false
    bundles:            [ BrouwkuypDashboardBundle ]
    filters:
        less:
            node:       '%node_path%'
            node_paths: [ '%node_modules_path%' ]
            apply_to:   '\.less$'
        cssrewrite: ~
#        cssrewrite:
#            apply_to: '\.(css|scss|sass)$'
    assets:
        bootstrap_css:
            inputs:
                - '%kernel.root_dir%/../src/Brouwkuyp/Bundle/DashboardBundle/Resources/public/less/bootstrap.less'
            filters:
                - less
                - cssrewrite
            output: 'css/bootstrap.css'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   '%database_driver%'
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset:  UTF8

        types:
            brouwkuyp_datetime: Brouwkuyp\Bundle\ServiceBundle\Doctrine\Type\DateTimeType

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true

        dql:
            datetime_functions:
                date: DoctrineExtensions\Query\Mysql\Date

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'
    spool:     { type: memory }

# Doctrine extentions
stof_doctrine_extensions:
    orm:
        default:
            timestampable:  true

braincrafted_bootstrap:
    jquery_path:            '%kernel.root_dir%/../components/jquery/jquery.min.js'
    customize:
        variables_file:     '%kernel.root_dir%/../src/Brouwkuyp/Bundle/DashboardBundle/Resources/public/less/variables.less'
        bootstrap_output:   '%kernel.root_dir%/../src/Brouwkuyp/Bundle/DashboardBundle/Resources/public/less/bootstrap.less'
