Brouwkuyp\Bundle\ServiceBundle\Entity\Batch:
    type: entity
    table: batch
    repositoryClass: Brouwkuyp\Bundle\ServiceBundle\Repository\BatchRepository

    id:
        id:
            type:           integer
            generator:
                strategy:   AUTO

    fields:
        # gedmo fields
        createdAt:
            column:         created_at
            type:           datetime
            gedmo:
                timestampable:
                    on:     create

    manyToOne:
        controlRecipe:
            targetEntity:   ControlRecipe
            mappedBy:       batch
            joinColumn:
                name:       control_recipe_id
