Brouwkuyp\Bundle\ServiceBundle\Entity\ControlRecipe:
    type: entity
    table: control_recipe
    repositoryClass: Brouwkuyp\Bundle\ServiceBundle\Repository\ControlRecipeRepository

    id:
        id:
            type:           integer
            generator:
                strategy:   AUTO

    fields:
        name:
            type:       string
            length:     120
        version:
            type: 	    integer
        remarks:
            type:	    text
            nullable:   true

    oneToOne:
        procedure:
            targetEntity: Procedure
#        formula:
#            targetEntity: Formula
