Brouwkuyp\Bundle\ServiceBundle\Entity\Log:
    type: entity
    table: log
    repositoryClass: Brouwkuyp\Bundle\ServiceBundle\Repository\LogRepository

    id:
        createdAt:
            column:     created_at
            type:       brouwkuyp_datetime
        topic:
            type:       string
            length:     120
        value:
            type:       string
            length:     120

    manyToOne:
        batch:
            targetEntity:   Batch
